version: '3.8'

services:
  pieces-os:
    image: wisdgod/pieces-os-go:latest
    container_name: pieces-os
    restart: unless-stopped
    ports:
      - "${PORT:-8787}:8787"
    environment:
      - TZ=Asia/Shanghai
      - PORT=8787
      - API_PREFIX=${API_PREFIX:-/v1/}
      - MIN_POOL_SIZE=${MIN_POOL_SIZE:-5}
      - MAX_POOL_SIZE=${MAX_POOL_SIZE:-20}
      - SCALE_INTERVAL=${SCALE_INTERVAL:-30}
      - API_KEY=${API_KEY}
      - DEBUG=${DEBUG:-false}
      - LOG_FILE=/app/logs/pieces-os.log
      - DEFAULT_MODEL=${DEFAULT_MODEL:-}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - TIMEOUT=${TIMEOUT:-30}
    volumes:
      - pieces_logs:/app/logs
    networks:
      - pieces-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  pieces-network:
    driver: bridge
    name: pieces-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  pieces_logs:
    name: pieces_logs